### ISSUE TITLE
Typo in default host value

### ISSUE THREAD

**Issue by zubkov-andrei** [rjuju/pg_validate_extupgrade#1]
Hello, Julien!

This tool looks very useful for me, thank you!
I was unable to run it without specifying the host. It hangs trying to connect on '27.0.0.1'. It seems like a typo in src/lib.rs:56

**Comment by rjuju** [comment]
Hi Andrei,

Thanks a lot!

You're right, that's an unfortunate typo.  I always have a PGHOST using some custom scripts set so I never hit that problem.

I just pushed a commit to fix the problem, thanks!  Let me know if that also fixes the problem for you.

While thinking about it, I think that postgres default behavior is to fallback on a unix socket on unix and localhost on windows.  I'll look deeper in both rust-postgres and libpq default parameter to improve that part.

**Comment by zubkov-andrei** [comment]
Thank you, Julien! This solved connection problem.

**Comment by rjuju** [comment]
Great, thanks for the confirmation!
