### ISSUE TITLE
function pg_get_statisticsobjdef_columns(oid) does not exist

### ISSUE THREAD

**Issue by zubkov-andrei** [rjuju/pg_validate_extupgrade#2]
Hi, Julien!

I'm trying _pg_validate_extupgrade_ on PG13:

```
postgres=# select version();
                                                 version                                                 
---------------------------------------------------------------------------------------------------------
 PostgreSQL 13.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
(1 row)
```
And it fails with an error on _pg_get_statisticsobjdef_columns_ function:
```
Connected, server version 130002
thread 'main' panicked at 'Could net get pg_statistic_ext rows: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42883), message: "function pg_get_statisticsobjdef_columns(oid) does not exist", detail: None, hint: Some("No function matches the given name and argument types. You might need to add explicit type casts."), position: Some(Original(92)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_func.c"), line: Some(627), routine: Some("ParseFuncOrColumn") }) }', src/extension/pg_statistic_ext.rs:44:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Am I doing something wrong?

**Comment by rjuju** [comment]
Hi Andrei,

You're not doing anything wrong.  I checked all the catalogs column to make sure that they were only used in the appropriate version, but I didn't do so for the function used to deparse some fields.  This function were added in pg 14 when support for extended statistics on expression were added.  I'll fix it, thanks a lot for the report!

**Comment by rjuju** [comment]
I just pushed https://github.com/rjuju/pg_validate_extupgrade/commit/490faa51c37b6996eb3786592e13d49902b61caf which solves this problem and a few other I found when running some more test with pg 13.

I'm not confident that my broken extension handles all the use cases, so let me know if you find other problems!

**Comment by zubkov-andrei** [comment]
Julien, thank you! Cool, now it works as expected.

**Comment by rjuju** [comment]
Good news, thanks a lot Andrei!
