### ISSUE TITLE
file not found for module `guc`

### ISSUE THREAD

**Issue by zubkov-andrei** [rjuju/pg_validate_extupgrade#4]
Hi, Julien!

It seems, last commit in a master branch 6b84639 is broken something.. In my case building fails with a bunch of errors starting with
```
error[E0583]: file not found for module `guc`
  --> src/lib.rs:26:1
   |
26 | mod guc;
   | ^^^^^^^^
   |
   = help: to create the module `guc`, create file "src/guc.rs"
```
Best regards, Andrei

**Comment by rjuju** [comment]
Hi Andrei,

Oops, I forgot to include that file in the last commit.  I just pushed it, thanks a lot for the report!

FTR this is a new check done to make sure that no GUC change is visible in the current connection after the extension script is run.

**Comment by zubkov-andrei** [comment]
This is a very important check.
Build is ok right now, thank you!

**Comment by rjuju** [comment]
Thanks!
