### ISSUE TITLE
Operator classes/families with the same name

### ISSUE THREAD

**Issue by zachasme** [rjuju/pg_validate_extupgrade#6]
I'm using this tool to validate my extension [zachasme/h3-pg](https://github.com/zachasme/h3-pg), and it is much better than old my scripts for comparing upgrades and installs. The output is extremely helpful!

I've been trying to debug a specific problem, and I can't quite figure out if it is an issue with `pg_validate_extupgrade` or my extension:

I have a branch where I've renamed some operator classes and families such that they share the same name, similar to `jsonb_ops` which has the same name across `btree`, `hash` and `gin` for example. See the change here: https://github.com/zachasme/h3-pg/pull/98/files

When I validate the upgrade locally I get the error:

```sql
- mismatch found for Extension h3:
  - in opfamilies:
    installed and upgraded both have 2 OpFamily but some mismatch in them:
      - mismatch found for OpFamily public.h3index_ops:
        - in opfmethod:
          - btree
          + hash
```

The test passes in CI, however. I suspect it might depend on the order in which the opfmethods are returned.

I have attempted to dig through the codebase and create a failing test, but I can't quite figure out how.

Can you shed some light on this?

**Comment by rjuju** [comment]
Hi,

Thanks a lot!  I also needed something to validate complex extension upgrades, so I'm happy it helps other people too.


I agree with you, the current behavior is to assume that an opfamily, identified by schema + opfamily name is unique, while it should only be unique for a given access method too, thus the invalid output you're getting.  I will fix that as soon as I can.

To recreate a test, I think that you need to update (rename as you did in your extension) the row with the lowest ctid, so the next seq scan will return the rows in a different order.

**Comment by rjuju** [comment]
I just pushed at fix at https://github.com/rjuju/pg_validate_extupgrade/commit/0bbacb3f694be0fae3a049cbbd2196451b142418, could you check to make sure it also fixes the problem for you?

FTR I was able to create a small reproducer, but I needed to use 3 operator families and not just 2.

**Comment by zachasme** [comment]
Hi, @rjuju. That was fast, and it did fix the problem for me! 👍🏿 Thanks again for this excellent tool.

**Comment by rjuju** [comment]
Great news, thanks a lot!

**Comment by zachasme** [comment]
Errors have begun popping up again, no longer for `opfamilies` but instead for `opclasses`:

```
- mismatch found for Extension h3:
  - in opclasses:
    installed and upgraded both have 2 OpClass but some mismatch in them:
      - mismatch found for OpClass public.h3index_ops:
        - in opcmethod:
          - btree
          + hash
```

Is it possible that adding `|| ' USING ' || am.amname"` is also required for opclass?

**Comment by rjuju** [comment]
Good catch again, thanks a lot for the report!

Commit 8d23a3e15be866625f3a3caed92ae1b53e764356 should fix the issue.

**Comment by zachasme** [comment]
Yup, that fixed it, thanks @rjuju!

**Comment by rjuju** [comment]
Great, thanks for the confirmation!
